### ISSUE TITLE
Initial Sales Price

### ISSUE THREAD

**Issue by ManangosCoin** [BenGOsborn/Pinata-Bulk-NFT#2]
Can this script set an initial sales price for each NFT?   Or  will I have to manually set NFT for sale after using this script?

**Comment by BenGOsborn** [comment]
The script itself just mints the NFT's, it'll be entirely up to you to sell them by uploading the contract to OpenSea or some other NFT marketplace. On these marketplaces, you will have to manually set the price of the NFT's as far as I am aware.
